'''
Auto-generated by afw_media: plays back "example1.afwframes" using afw.

Usage:
    python3 example1.py

Requires afw.py to be importable (same directory, or on PYTHONPATH).
Works with both truecolor and old() compatibility mode: this script
never bakes in a color mode, it just feeds raw RGB into Canvas,
call afw.old() before running if your terminal needs 256-color
fallback.
'''
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import afw as afw  # noqa: E402


class AfwFrames:
    """Reads a .afwframes asset produced by the afw_media Rust tool.

    Frames are fixed-size (cols*rows*6 bytes each), so any frame index
    can be seeked to directly without scanning prior frames; this
    matters for scrubbing or looping playback of long converted videos.
    """

    HEADER_FORMAT = "<4sIIIf"
    HEADER_SIZE = struct.calcsize(HEADER_FORMAT)

    def __init__(self, path):
        self._f = open(path, "rb")
        header = self._f.read(self.HEADER_SIZE)
        if len(header) < self.HEADER_SIZE:
            raise ValueError(f"{path}: file too small to be a valid .afwframes asset")
        magic, cols, rows, frame_count, fps = struct.unpack(self.HEADER_FORMAT, header)
        if magic != b"AFW1":
            raise ValueError(f"{path}: not an AFW1 asset (bad magic bytes)")
        self.cols = cols
        self.rows = rows
        self.frame_count = frame_count
        self.fps = fps
        self._frame_bytes = cols * rows * 6
        self._data_start = self.HEADER_SIZE

    def __len__(self):
        return self.frame_count

    def close(self):
        self._f.close()

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()

    def read_frame(self, index: int) -> bytes:
        """Returns the raw cell bytes for `index`, clamped into range so
        a caller looping slightly past the end (off-by-one, or a video
        whose reported frame count was approximate) degrades to repeating
        the last frame instead of raising."""
        if self.frame_count == 0:
            raise ValueError("asset has zero frames")
        index = max(0, min(index, self.frame_count - 1))
        offset = self._data_start + index * self._frame_bytes
        self._f.seek(offset)
        data = self._f.read(self._frame_bytes)
        if len(data) < self._frame_bytes:
            raise IOError(
                f"truncated .afwframes asset: expected {self._frame_bytes} bytes "
                f"for frame {index}, got {len(data)} (file may be corrupt or still writing)"
            )
        return data

    def draw_frame(self, canvas: "afw.Canvas", index: int, *, x_offset: int = 0, y_offset: int = 0) -> None:
        """Draws frame `index` onto `canvas` using put_subpixel, matching
        exactly what afw_media computed on the Rust side. x_offset/y_offset
        let the asset be composited anywhere on a larger canvas rather
        than always starting at (0, 0)."""
        data = self.read_frame(index)
        cols, rows = self.cols, self.rows
        mv = memoryview(data)
        i = 0
        for cy in range(rows):
            for cx in range(cols):
                tr, tg, tb, br, bg, bb = mv[i:i + 6]
                i += 6
                top = afw.Color(tr, tg, tb)
                bottom = afw.Color(br, bg, bb)
                canvas.put_subpixel(x_offset + cx, (y_offset + cy) * 2, top)
                canvas.put_subpixel(x_offset + cx, (y_offset + cy) * 2 + 1, bottom)


def main() -> None:
    asset_path = Path(__file__).resolve().parent / "example1.afwframes"
    with AfwFrames(asset_path) as frames:
        is_video = frames.frame_count > 1

        app = afw.App(target_fps=frames.fps if is_video and frames.fps > 0 else 60.0)

        state = {"index": 0}

        @app.on_update
        def update(dt):
            if is_video:
                state["index"] = (state["index"] + 1) % frames.frame_count
            else:
                app.stop() if app.frame_count > 1 else None

        @app.on_render
        def render(canvas):
            frames.draw_frame(canvas, state["index"])

        @app.on_key
        def handle_key(ev):
            if ev.key == afw.Key.ESCAPE or ev.is_char("q") or ev.key == afw.Key.CTRL_C:
                app.stop()

        app.run()


if __name__ == "__main__":
    main()
